name: 'Z-Wave Switch BTSR LED (CS Mod)'
packageKey: 'zwave-switch-cs'
description: 'GE, HomeSeer, Honeywell, Jasco, Inovelli, Remotec and Zooz Z-wave switches with automatable LED control'
vendorSupportInformation: 'Developer: BigThunderSR (fork of philh30/csstup)<br>Web: <a href="https://github.com/BigThunderSR/ST-Edge-Drivers">GitHub repo</a><br>Upstream: <a href="https://github.com/csstup/philh30_ST-Edge-Drivers">csstup/philh30_ST-Edge-Drivers</a><br><br>Adds automatable LED color and intensity capabilities for compatible GE/Jasco models.<br><br>Supports:<br>- GE/Jasco/Honeywell/Ultrapro actuators<br>- HomeSeer FLS100+/FLS100+G2<br>- Inovelli LZW36/LZW45/NZW97<br>- Remotec ZFM80<br>- Zooz ZEN32/ZEN51'
permissions:
  zwave: {}
